language: python
sudo: false
cache: pip
python:
- 3.6
- 3.7
- 3.8
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: __token__
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
